### PR TITLE
fix: added logic on pathProps to re-instance nodes once `args` change

### LINKED ISSUE #366: Re-instance THREE instances via args prop reactivity
### Description

As a developer using TresJS, I would like to change reactively the constructor params via args prop, which is not possible at the moment.

```ts
<script lang="ts" setup>
// renderer.domElement is undefined at the beginning. 
</script>

<template>
  <TresOrbitControls  :args="[activeCamera || camera, renderer?.domElement || domElement]" />
 </template>
 ```

### Suggested solution

Add logic to `nodeOps` to re-instance the THREE object when `args` change

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by alvarosabu**
Closes #366

### CODE REVIEW

File: src/core/nodeOps.ts [hunk 1]
```diff
@@ -184,6 +184,14 @@ export const nodeOps: RendererOptions<TresObject, TresObject> = {
...
       let target = root?.[finalKey]
 
+      if (key === 'args' && !deepArrayEqual(_prevValue, nextValue)) {
+        const prevNode = node as TresObject3D
+
+        if (node.type && nextValue.length > 0) {
+          root = Object.assign(prevNode, new catalogue.value[node.type](...nextValue))
+        }
+      }
+
```
Comment (enpitsuLin) [inline src/core/nodeOps.ts:194]: I think there should be premature return, or just add a condition on L220

**Review by enpitsuLin — CHANGES_REQUESTED** [review]

File: src/core/nodeOps.ts (hunk 1 above)
Comment (alvarosabu) [reply src/core/nodeOps.ts:195]: Done

**Review by enpitsuLin — APPROVED** [review]

**Review by enpitsuLin — APPROVED** [review]
