### PR TITLE
fix(leches): persist textfield values and support PgUp/PgDn keys

### LINKED ISSUE #1404: [BUG] Textfield values reset after keyboard input (PgUp/PgDn) and blur
### Describe the bug

When clicking on textfield controls in Leches (like position, zoom, near, far) and modifying values using Page Up and Page Down keys, the changes work momentarily while focused but automatically reset to original values after clicking outside the field or losing focus.

Additionally:
Page Up/Page Down keys are not fully implemented - the internal state changes but the display doesn't update immediately
After pressing PgUp/PgDn, the textfield shows no number, making it unclear what value is set
Changes are lost on blur, defeating the purpose of keyboard shortcuts for quick adjustments
I intend to submit a PR for this issue.

### Reproduction

http://localhost:5174/core/cameras/orthographic-camera

### Steps to reproduce

- Clone and install: pnpm install && pnpm build
- Start playground: pnpm --filter playground dev
- Navigate to Orthographic Camera demo (Core → Cameras → Orthographic Camera)
- Click on the position.x textfield
- Press Page Up 2-3 times (value changes: 1 → 11 → 21)
- Observe: Value shows "21" in textfield while focused ✓
- Click outside (on 3D canvas or another field)
- Expected: Value stays at "21" ✗
- Actual: Value resets back to "1" ✗

### System Info

```shell
OS: Windows 10/11
Browser: Chrome 120+ / Firefox 121+
Node: v20+
pnpm: v8+

Packages:
- @tresjs/core: latest
- @tresjs/leches: latest (affected)
- three: ^r128
- vue: ^3.3
```

### Used Package Manager

pnpm

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/Tresjs/.github/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://tresjs.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by BittuBarnwal7479**
Closes: #1404

### CODE REVIEW

**Comment by BittuBarnwal7479** [comment]
782d00e7-edbf-4769-9584-1a6188c4968d

**Comment by BittuBarnwal7479** [comment]
Recording 2026-04-21 035547

File: packages/leches/src/components/NumberControl.vue [hunk 1]
```diff
@@ -65,11 +65,25 @@ function onKeyDown(e: KeyboardEvent) {
...
+    e.preventDefault()
+    const newVal = clampValue(controlValue.value + step.value * 10 * modifier, props.control.min, props.control.max)
+    emit('change', newVal)
+    displayValue.value = formatter.value(newVal)
+  }
+  if (e.key === 'PageDown') {
+    e.preventDefault()
+    const newVal = clampValue(controlValue.value - step.value * 10 * modifier, props.control.min, props.control.max)
+    emit('change', newVal)
+    displayValue.value = formatter.value(newVal)
```
Comment (alvarosabu) [inline packages/leches/src/components/NumberControl.vue:86]: Small thing, Shift+PgUp ends up as step * 100 since Shift (×10) and PgUp (×10) stack. Probably not what we want. Should PgUp just ignore modifiers?

File: packages/leches/src/components/NumberControl.vue
Comment (alvarosabu) [inline packages/leches/src/components/NumberControl.vue:1]: @BittuBarnwal7479 could you please add tests for both files?

**Review by alvarosabu — CHANGES_REQUESTED** [review]
Hi @BittuBarnwal7479 thanks for contributing, couple of things before we can merge

File: packages/leches/src/components/NumberControl.vue (hunk 1 above)
Comment (BittuBarnwal7479) [reply packages/leches/src/components/NumberControl.vue:86]: I changed PageUp and PageDown to ignore modifiers in both NumberControl and VectorControl, so Shift+PgUp no longer stacks to x100.

File: packages/leches/src/components/NumberControl.vue
Comment (BittuBarnwal7479) [reply packages/leches/src/components/NumberControl.vue:1]: added tests, thanks for pointing this out.

**Review by alvarosabu — APPROVED** [review]
LGTM @BittuBarnwal7479 thanks a lot
